Remove WPS support
Using WPS functions causes link errors since esp8266 library version 2.4.0:

```
/var/folders/9q/kc98p7l11fgctj4y1b8t344h0000gn/T/arduino_build_185922/libraries/PersWiFiManager/PersWiFiManager.cpp.o: In function `PersWiFiManager::attemptConnection(String const&, String const&)':
/Users/peter/code/arduino/libraries/PersWiFiManager/PersWiFiManager.cpp:30: undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
/var/folders/9q/kc98p7l11fgctj4y1b8t344h0000gn/T/arduino_build_185922/libraries/PersWiFiManager/PersWiFiManager.cpp.o:(.text._ZNSt17_Function_handlerIFvvEZN15PersWiFiManager17setupWiFiHandlersEvEUlvE0_E9_M_invokeERKSt9_Any_data+0x3e): undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
collect2: error: ld returned 1 exit status
```